# Generated by Django 4.1 on 2022-08-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_name', models.CharField(max_length=100)),
                ('group_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
