# Generated by Django 4.1 on 2022-08-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(default='svrokt8f7k', max_length=10)),
                ('block_id', models.CharField(max_length=10)),
                ('unit_id', models.CharField(max_length=10)),
            ],
        ),
    ]
