# Generated by Django 4.1 on 2022-08-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_farmblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmblock',
            name='block_id',
            field=models.CharField(default='b0', max_length=10),
        ),
        migrations.AlterField(
            model_name='farmblock',
            name='block_name',
            field=models.CharField(default='q6mwefg8sw', max_length=10),
        ),
        migrations.AlterField(
            model_name='farmblock',
            name='unit_id',
            field=models.CharField(default='u0', max_length=10),
        ),
    ]
