# Generated by Django 4.1 on 2022-08-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_alter_farmblock_block_name_alter_farmblock_unit_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmblock',
            name='block_name',
            field=models.CharField(default='WSnj0QCTzA', max_length=10),
        ),
        migrations.AlterField(
            model_name='farmblock',
            name='unit_id',
            field=models.CharField(default='u1', max_length=10),
        ),
    ]
