# Generated by Django 4.1 on 2022-08-20 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0009_alter_farmblock_block_id_alter_farmblock_block_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmblock',
            name='block_name',
            field=models.CharField(default='2_Bdhe3gRA', max_length=10),
        ),
        migrations.CreateModel(
            name='FarmModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(default='zbCZrcjuUg', max_length=10)),
                ('module_id', models.CharField(max_length=15)),
                ('block_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.farmblock')),
            ],
        ),
        migrations.CreateModel(
            name='AddSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=100)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.sensor')),
            ],
        ),
    ]
